/**
 * Limb structural matching: PCA axis + large-structure anchors.
 *
 * This is intentionally not a local surface descriptor matcher. For arms / legs
 * generated by Page2, local shape and small protrusions can change, while the
 * stable information is the limb axis, the proximal/distal endpoints, and the
 * large bend plane (elbow/knee facing direction).  The matcher therefore builds
 * three semantic anchors:
 *   1. root/proximal endpoint (shoulder / hip)
 *   2. bend centerline point (elbow / knee)
 *   3. distal endpoint (palm / foot)
 */

import type { LandmarkCandidate, Vec3 } from './types';
import { computeAxialFrame } from './axialFrame';
import { applyTransform, computeLandmarkAlignment, type AlignmentMode } from './alignment';

export interface LimbStructureMatchOptions {
  /** Target limb region vertices, typically from SAM3 mask reprojection. */
  tarConstraintVertices?: Set<number>;
  /** Optional torso/body vertices used to decide which endpoint is root. */
  tarBodyVertices?: Set<number>;
  /** Alignment mode. Default: similarity. */
  mode?: AlignmentMode;
  /** Endpoint cluster width as a fraction of PCA axis range. Default: 0.08. */
  endpointFraction?: number;
  /** Number of large axial slices used for centerline/bend detection. Default: 13. */
  axialBins?: number;
}

export interface LimbAnchorSet {
  root: AnchorPoint;
  bend: AnchorPoint;
  end: AnchorPoint;
  axis: Vec3;
  axisLength: number;
  bendStrength: number;
}

export interface AnchorPoint {
  kind: 'root' | 'bend' | 'end';
  vertex: number;
  position: Vec3;
}

export interface LimbStructureMatchResult {
  pairs: LandmarkCandidate[];
  matrix4x4: number[][] | null;
  rmse: number;
  thresholdUsed: number;
  iterationsRun: number;
  rawSrcSamples: number;
  rawTarSamples: number;
  bestInlierCount: number;
  srcAnchors: LimbAnchorSet | null;
  tarAnchors: LimbAnchorSet | null;
  diagnostics: Record<string, unknown>;
}

interface RawLimbStructure {
  lower: AnchorPoint;
  upper: AnchorPoint;
  bend: AnchorPoint;
  axis: Vec3;
  axisLength: number;
  bendStrength: number;
}

interface SliceCenter {
  bin: number;
  t: number;
  count: number;
  position: Vec3;
  nearestVertex: number;
}

const EPS = 1e-9;

export function matchLimbStructureToWhole(
  src: { vertices: Vec3[] },
  tar: { vertices: Vec3[] },
  options: LimbStructureMatchOptions = {},
): LimbStructureMatchResult {
  const mode = options.mode ?? 'similarity';
  const srcIndices = allIndices(src.vertices.length);
  const tarIndices = options.tarConstraintVertices && options.tarConstraintVertices.size > 0
    ? Array.from(options.tarConstraintVertices).filter((i) => i >= 0 && i < tar.vertices.length)
    : allIndices(tar.vertices.length);

  if (srcIndices.length < 3 || tarIndices.length < 3) {
    return emptyResult('not-enough-vertices');
  }

  const srcRaw = detectRawLimbStructure(src.vertices, srcIndices, options);
  const tarRaw = detectRawLimbStructure(tar.vertices, tarIndices, options);
  if (!srcRaw || !tarRaw) return emptyResult('structure-detect-failed');

  const bodyCentroid = options.tarBodyVertices && options.tarBodyVertices.size > 0
    ? centroidOfIndices(tar.vertices, Array.from(options.tarBodyVertices))
    : centroidOfIndices(tar.vertices, allIndices(tar.vertices.length, 20000));

  const tarLowerRootDist = dist3(tarRaw.lower.position, bodyCentroid);
  const tarUpperRootDist = dist3(tarRaw.upper.position, bodyCentroid);
  const tarRootIsLower = tarLowerRootDist <= tarUpperRootDist;
  const tarAnchors = orientAnchors(tarRaw, tarRootIsLower);

  // Source usually arrives in roughly the same world-facing pose as target, but
  // its origin/scale/detail may differ. Choose the source endpoint orientation
  // whose PCA root→end direction is most parallel to the target root→end axis.
  const tarDir = norm3(sub3(tarAnchors.end.position, tarAnchors.root.position));
  const srcLowerToUpper = norm3(sub3(srcRaw.upper.position, srcRaw.lower.position));
  const srcRootIsLower = dot3(srcLowerToUpper, tarDir) >= 0;
  const srcAnchors = orientAnchors(srcRaw, srcRootIsLower);

  const sourcePoints = [srcAnchors.root.position, srcAnchors.bend.position, srcAnchors.end.position];
  const targetPoints = [tarAnchors.root.position, tarAnchors.bend.position, tarAnchors.end.position];

  let matrix4x4: number[][];
  try {
    matrix4x4 = computeLandmarkAlignment(sourcePoints, targetPoints, mode).matrix4x4;
  } catch {
    return {
      ...emptyResult('degenerate-anchor-fit'),
      srcAnchors,
      tarAnchors,
      rawSrcSamples: 3,
      rawTarSamples: 3,
    };
  }

  const errors = sourcePoints.map((p, i) => dist3(applyTransform(p, matrix4x4), targetPoints[i]));
  const rmse = Math.sqrt(errors.reduce((s, v) => s + v * v, 0) / errors.length);
  const pairs = makePairs(srcAnchors, tarAnchors, errors);

  return {
    pairs,
    matrix4x4,
    rmse,
    thresholdUsed: 0,
    iterationsRun: 1,
    rawSrcSamples: 3,
    rawTarSamples: 3,
    bestInlierCount: 3,
    srcAnchors,
    tarAnchors,
    diagnostics: {
      mode,
      targetRootBy: options.tarBodyVertices && options.tarBodyVertices.size > 0 ? 'body-region' : 'target-centroid',
      tarEndpointDistancesToBody: {
        lower: tarLowerRootDist,
        upper: tarUpperRootDist,
      },
      srcRootIsLower,
      tarRootIsLower,
      srcBendStrength: srcAnchors.bendStrength,
      tarBendStrength: tarAnchors.bendStrength,
      errors,
    },
  };
}

function detectRawLimbStructure(
  vertices: Vec3[],
  indices: number[],
  options: LimbStructureMatchOptions,
): RawLimbStructure | null {
  if (indices.length < 3) return null;
  const frame = computeAxialFrame(vertices, indices);
  const axisLength = Math.max(frame.axialMax - frame.axialMin, EPS);
  const endpointFraction = clamp(options.endpointFraction ?? 0.08, 0.02, 0.2);
  const bins = Math.max(7, Math.floor(options.axialBins ?? 13));

  const lowerCut = frame.axialMin + endpointFraction * axisLength;
  const upperCut = frame.axialMax - endpointFraction * axisLength;
  const lowerIndices: number[] = [];
  const upperIndices: number[] = [];
  const binned: number[][] = Array.from({ length: bins }, () => []);

  for (const idx of indices) {
    const p = vertices[idx];
    const a = dot3(sub3(p, frame.centroid), frame.axis);
    if (a <= lowerCut) lowerIndices.push(idx);
    if (a >= upperCut) upperIndices.push(idx);
    const t = clamp((a - frame.axialMin) / axisLength, 0, 1);
    const bin = Math.min(bins - 1, Math.floor(t * bins));
    binned[bin].push(idx);
  }

  const lower = anchorFromCluster('root', vertices, lowerIndices.length > 0 ? lowerIndices : [indices[0]]);
  const upper = anchorFromCluster('end', vertices, upperIndices.length > 0 ? upperIndices : [indices[indices.length - 1]]);
  const slices: SliceCenter[] = [];
  for (let bin = 0; bin < binned.length; bin++) {
    const group = binned[bin];
    if (group.length === 0) continue;
    const position = centroidOfIndices(vertices, group);
    slices.push({
      bin,
      t: (bin + 0.5) / bins,
      count: group.length,
      position,
      nearestVertex: nearestVertex(vertices, group, position),
    });
  }

  const chord = sub3(upper.position, lower.position);
  const chordLen = Math.max(normLen3(chord), EPS);
  let best: SliceCenter | null = null;
  let bestDist = -1;
  for (const slice of slices) {
    if (slice.t < 0.18 || slice.t > 0.82) continue;
    const d = distanceToLine(slice.position, lower.position, upper.position);
    // Prefer large-scale middle bends. Count weighting suppresses tiny isolated
    // detail slices; endpoint taper is ignored by the t-window above.
    const middleWeight = 1 - Math.abs(slice.t - 0.5) * 0.35;
    const score = d * middleWeight * Math.sqrt(Math.max(slice.count, 1));
    if (score > bestDist) {
      bestDist = score;
      best = slice;
    }
  }
  if (!best) best = slices[Math.floor(slices.length / 2)] ?? null;
  if (!best) return null;

  const bend: AnchorPoint = {
    kind: 'bend',
    vertex: best.nearestVertex,
    position: best.position,
  };
  const bendStrength = distanceToLine(bend.position, lower.position, upper.position) / chordLen;
  return {
    lower: { ...lower, kind: 'root' },
    upper: { ...upper, kind: 'end' },
    bend,
    axis: frame.axis,
    axisLength,
    bendStrength,
  };
}

function orientAnchors(raw: RawLimbStructure, rootIsLower: boolean): LimbAnchorSet {
  const rootRaw = rootIsLower ? raw.lower : raw.upper;
  const endRaw = rootIsLower ? raw.upper : raw.lower;
  const root: AnchorPoint = { kind: 'root', vertex: rootRaw.vertex, position: rootRaw.position };
  const end: AnchorPoint = { kind: 'end', vertex: endRaw.vertex, position: endRaw.position };
  const axis = norm3(sub3(end.position, root.position));
  return {
    root,
    bend: raw.bend,
    end,
    axis,
    axisLength: raw.axisLength,
    bendStrength: raw.bendStrength,
  };
}

function makePairs(src: LimbAnchorSet, tar: LimbAnchorSet, errors: number[]): LandmarkCandidate[] {
  const anchors: Array<[AnchorPoint, AnchorPoint]> = [
    [src.root, tar.root],
    [src.bend, tar.bend],
    [src.end, tar.end],
  ];
  return anchors.map(([s, t], i) => ({
    srcVertex: s.vertex,
    srcPosition: s.position,
    tarVertex: t.vertex,
    tarPosition: t.position,
    confidence: Math.max(0.55, 0.98 - i * 0.04),
    descriptorDist: errors[i] ?? 0,
    suggestAccept: true,
  }));
}

function emptyResult(reason: string): LimbStructureMatchResult {
  return {
    pairs: [],
    matrix4x4: null,
    rmse: Infinity,
    thresholdUsed: 0,
    iterationsRun: 0,
    rawSrcSamples: 0,
    rawTarSamples: 0,
    bestInlierCount: 0,
    srcAnchors: null,
    tarAnchors: null,
    diagnostics: { reason },
  };
}

function anchorFromCluster(kind: AnchorPoint['kind'], vertices: Vec3[], indices: number[]): AnchorPoint {
  const position = centroidOfIndices(vertices, indices);
  return { kind, vertex: nearestVertex(vertices, indices, position), position };
}

function allIndices(n: number, maxCount?: number): number[] {
  if (!maxCount || n <= maxCount) return Array.from({ length: n }, (_, i) => i);
  const out: number[] = [];
  const stride = n / maxCount;
  for (let i = 0; i < maxCount; i++) out.push(Math.min(n - 1, Math.floor(i * stride)));
  return out;
}

function centroidOfIndices(vertices: Vec3[], indices: number[]): Vec3 {
  if (indices.length === 0) return [0, 0, 0];
  let x = 0, y = 0, z = 0;
  let count = 0;
  for (const idx of indices) {
    const p = vertices[idx];
    if (!p) continue;
    x += p[0]; y += p[1]; z += p[2]; count++;
  }
  if (count === 0) return [0, 0, 0];
  return [x / count, y / count, z / count];
}

function nearestVertex(vertices: Vec3[], indices: number[], position: Vec3): number {
  let best = indices[0] ?? 0;
  let bestD = Infinity;
  for (const idx of indices) {
    const d = distSq3(vertices[idx], position);
    if (d < bestD) {
      bestD = d;
      best = idx;
    }
  }
  return best;
}

function distanceToLine(p: Vec3, a: Vec3, b: Vec3): number {
  const ab = sub3(b, a);
  const denom = Math.max(dot3(ab, ab), EPS);
  const t = clamp(dot3(sub3(p, a), ab) / denom, 0, 1);
  const q: Vec3 = [a[0] + ab[0] * t, a[1] + ab[1] * t, a[2] + ab[2] * t];
  return dist3(p, q);
}

function sub3(a: Vec3, b: Vec3): Vec3 {
  return [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
}

function dot3(a: Vec3, b: Vec3): number {
  return a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
}

function normLen3(a: Vec3): number {
  return Math.sqrt(dot3(a, a));
}

function norm3(a: Vec3): Vec3 {
  const len = normLen3(a);
  return len > EPS ? [a[0] / len, a[1] / len, a[2] / len] : [1, 0, 0];
}

function distSq3(a: Vec3, b: Vec3): number {
  const dx = a[0] - b[0];
  const dy = a[1] - b[1];
  const dz = a[2] - b[2];
  return dx * dx + dy * dy + dz * dz;
}

function dist3(a: Vec3, b: Vec3): number {
  return Math.sqrt(distSq3(a, b));
}

function clamp(v: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, v));
}
